# Generated by Django 6.0.4 on 2026-04-09 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('onboard_date', models.DateField(verbose_name='到職日')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='離職日')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在職')),
            ],
        ),
        migrations.CreateModel(
            name='SystemApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='系統名稱')),
                ('url', models.URLField(blank=True, verbose_name='系統網址')),
                ('description', models.TextField(blank=True, verbose_name='備註說明')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='登入帳號')),
                ('password', models.CharField(max_length=255, verbose_name='加密密碼')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='權限是否已取消')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='所屬員工')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.systemapp', verbose_name='所屬系統')),
            ],
            options={
                'unique_together': {('employee', 'system')},
            },
        ),
    ]
