# Generated by Django 6.0.4 on 2026-04-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '帳戶', 'verbose_name_plural': '帳戶'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '員工', 'verbose_name_plural': '員工'},
        ),
        migrations.AlterModelOptions(
            name='systemapp',
            options={'verbose_name': '系統', 'verbose_name_plural': '系統'},
        ),
    ]
