# Generated by Django 6.0.4 on 2026-04-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_is_revoked_to_has_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='電子信箱'),
            preserve_default=False,
        ),
    ]
